require "rails_helper"

RSpec.describe Proposal, type: :model do
  describe "associations" do
    it { should belong_to(:user) }
    it { should belong_to(:client).optional }
  end

  describe "validations" do
    it { should validate_presence_of(:title) }
    # share_token is auto-generated by callback, so presence is guaranteed

    context "when fixed pricing" do
      subject { build(:proposal, pricing_type: :fixed) }
      it { should validate_presence_of(:amount) }
      it { should validate_numericality_of(:amount).is_greater_than(0) }
    end

    context "when hourly pricing" do
      subject { build(:proposal, pricing_type: :hourly, amount: nil) }
      it { should validate_presence_of(:hourly_rate) }
      it { should validate_numericality_of(:hourly_rate).is_greater_than(0) }
    end

    context "when not draft" do
      subject { build(:proposal, :sent) }
      it { should validate_presence_of(:client) }
    end

    context "when draft" do
      subject { build(:proposal, status: :draft) }
      it { should_not validate_presence_of(:client) }
    end
  end

  describe "enums" do
    it { should define_enum_for(:status).with_values(draft: 0, sent: 1, viewed: 2, accepted: 3, declined: 4, expired: 5) }
    it { should define_enum_for(:pricing_type).with_values(fixed: 0, hourly: 1) }
  end

  describe "callbacks" do
    it "generates a share_token before validation on create" do
      proposal = build(:proposal, share_token: nil)
      proposal.valid?
      expect(proposal.share_token).to be_present
    end
  end

  describe "#total_amount" do
    context "with fixed pricing" do
      it "returns the amount" do
        proposal = build(:proposal, pricing_type: :fixed, amount: 5000)
        expect(proposal.total_amount).to eq(5000)
      end
    end

    context "with hourly pricing" do
      it "returns hourly_rate * estimated_hours" do
        proposal = build(:proposal, :hourly, hourly_rate: 100, estimated_hours: 40)
        expect(proposal.total_amount).to eq(4000)
      end

      it "returns 0 when estimated_hours is nil" do
        proposal = build(:proposal, :hourly, hourly_rate: 100, estimated_hours: nil)
        expect(proposal.total_amount).to eq(0)
      end
    end
  end

  describe "#mark_as_sent!" do
    it "changes status from draft to sent" do
      proposal = create(:proposal, :with_client, status: :draft)
      proposal.mark_as_sent!
      expect(proposal.reload).to be_sent
      expect(proposal.sent_at).to be_present
    end

    it "does not change status if already sent" do
      proposal = create(:proposal, :sent)
      original_sent_at = proposal.sent_at
      proposal.mark_as_sent!
      expect(proposal.reload.sent_at).to eq(original_sent_at)
    end
  end

  describe "#mark_as_viewed!" do
    it "changes status from sent to viewed" do
      proposal = create(:proposal, :sent)
      proposal.mark_as_viewed!
      expect(proposal.reload).to be_viewed
      expect(proposal.viewed_at).to be_present
    end

    it "does not change status if already viewed" do
      proposal = create(:proposal, :viewed)
      original_viewed_at = proposal.viewed_at
      proposal.mark_as_viewed!
      expect(proposal.reload.viewed_at).to eq(original_viewed_at)
    end

    it "does not change status if draft" do
      proposal = create(:proposal, status: :draft)
      proposal.mark_as_viewed!
      expect(proposal.reload).to be_draft
    end
  end

  describe "#accept!" do
    it "changes status to accepted and records signature" do
      proposal = create(:proposal, :sent)
      proposal.accept!(signature_name: "John Doe", signature_ip: "192.168.1.1")

      expect(proposal.reload).to be_accepted
      expect(proposal.signature_name).to eq("John Doe")
      expect(proposal.signature_ip).to eq("192.168.1.1")
      expect(proposal.signature_at).to be_present
    end

    it "works when status is viewed" do
      proposal = create(:proposal, :viewed)
      proposal.accept!(signature_name: "Jane Doe", signature_ip: "192.168.1.2")
      expect(proposal.reload).to be_accepted
    end

    it "does not accept if draft" do
      proposal = create(:proposal, status: :draft)
      proposal.accept!(signature_name: "Test", signature_ip: "127.0.0.1")
      expect(proposal.reload).to be_draft
    end
  end

  describe "#expired?" do
    it "returns false when expires_at is nil" do
      proposal = build(:proposal, expires_at: nil)
      expect(proposal.expired?).to be false
    end

    it "returns true when expires_at is in the past" do
      proposal = build(:proposal, expires_at: 1.day.ago)
      expect(proposal.expired?).to be true
    end

    it "returns false when expires_at is in the future" do
      proposal = build(:proposal, expires_at: 1.day.from_now)
      expect(proposal.expired?).to be false
    end

    it "returns true when status is expired" do
      proposal = build(:proposal, status: :expired, expires_at: 1.day.from_now)
      expect(proposal.expired?).to be true
    end
  end

  describe "#can_be_viewed?" do
    it "returns true for sent proposals" do
      proposal = build(:proposal, :sent, expires_at: nil)
      expect(proposal.can_be_viewed?).to be true
    end

    it "returns true for viewed proposals" do
      proposal = build(:proposal, :viewed, expires_at: nil)
      expect(proposal.can_be_viewed?).to be true
    end

    it "returns false for draft proposals" do
      proposal = build(:proposal, status: :draft)
      expect(proposal.can_be_viewed?).to be false
    end

    it "returns false for expired proposals" do
      proposal = build(:proposal, :sent, expires_at: 1.day.ago)
      expect(proposal.can_be_viewed?).to be false
    end
  end

  describe "#can_be_accepted?" do
    it "returns true for sent proposals that are not expired" do
      proposal = build(:proposal, :sent, expires_at: nil)
      expect(proposal.can_be_accepted?).to be true
    end

    it "returns true for viewed proposals that are not expired" do
      proposal = build(:proposal, :viewed, expires_at: nil)
      expect(proposal.can_be_accepted?).to be true
    end

    it "returns false for accepted proposals" do
      proposal = build(:proposal, :accepted)
      expect(proposal.can_be_accepted?).to be false
    end

    it "returns false for expired proposals" do
      proposal = build(:proposal, :sent, expires_at: 1.day.ago)
      expect(proposal.can_be_accepted?).to be false
    end
  end
end
